// <auto-generated />
namespace Project_With_Angular.Migrations.provide
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Provider_create : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Provider_create));
        
        string IMigrationMetadata.Id
        {
            get { return "202010170957110_Provider_create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
